server:
  port: 8082
management:
  port: 8081
camel:
  springboot:
    name: RestService
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
api:
  path: '/camel'